version: 3
services:
  api:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/huisnow
      NODE_ENV: development
      PORT: 4000
    ports:
      - "4000:4000"
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules
  
  postgres:
    image: postgres:10.4
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: huisnow
    