version: "2"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: yarn start
    depends_on:
      - postgres
      - redis
    env_file: .env
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app
      - /app/node_modules

  search:
    build:
      context: ./services/search
      dockerfile: Dockerfile
    command: yarn start
    depends_on:
      - api
      - redis
    ports:
      - "4001:4001"
    volumes:
      - ./services/search:/app
      - /app/node_modules

  postgres:
    image: mdillon/postgis
    ports:
      - "35432:5432"
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: bitnami/redis
    ports:
      - "6370:6379"
    env_file: .env
    environment:
      - DISABLE_COMMANDS=
    volumes:
      - redisdata:/bitnami/redis/data

volumes:
  pgdata:
  redisdata:
